### ISSUE TITLE
Key secret api allociné

### ISSUE THREAD

**Issue by Hellsangels** [gromez/allocine-api#11]
Bonjour

Allociné à changé la clé partner et la key secrete.  Pour la clé partner je l'ai trouvé c'est celle ci 000042532791 Mais impossible de trouver la key secrete.

**Comment by gromez** [comment]
La nouvelle clé partner qui est utilisée est 100ED1DA33EB
J'ai aussi la clé secrète associée, mais malgré ça, ça n'a pas l'air de générer la bonne signature.
Il y a probablement eu un changement d'algo, j'essaye de voir ça dans les jours qui viennent.

**Comment by gromez** [comment]
C'est bon, nouvel algo analysé, ça fonctionne, je push les modifs prochainement.

**Comment by gromez** [comment]
https://github.com/gromez/allocine-api/commit/01d7c43454d8a534a50b866dedb353b1da6b3093

**Comment by Hellsangels** [comment]
Merci beaucoup de votre aide
