### ISSUE TITLE
showtimelist retourne NULL

### ISSUE THREAD

**Issue by Malinx95** [gromez/allocine-api#19]
Dans les exemple php, la fonction showtimelist() retourne null peut importe les ids ou dates.
J'essai de faire fonctionner cette fonction depuis quelques jour. Suis-je le seul pour qui cette fonctionnalité ne fonctionne pas ?
Il faut que j'arrive a faire fonctionner cette fonctionnalité pour que je puisse faire mon projet de développement web de 3eme année de License info !

**Comment by DecMoonFR** [comment]
Pour le moment l'API qui retourne les séances de cinéma ne fonctionne plus. Du coup normal que l'exemple soit HS.

**Comment by Malinx95** [comment]
Dommage j'en avais vraiment besoin ! Connaissez vous une autre solution pour récupérer les séance dans un cinéma ?

**Comment by Dammmien** [comment]
Hello,
Savez-vous ce qui a changé sur l'API ?
J'ai des erreurs 403 depuis quelques semaines sur ce endpoint, une idée de contournement ?

**Comment by gromez** [comment]
Un exemple utilisant l'API GraphQL est maintenant sur le projet : https://github.com/gromez/allocine-api/commit/84f238d55960f3ec8d276d795c51c70aafee731e

**Comment by abourtnik** [comment]
Hello,

Le endpoint **/showtimelist** retourne toujours une 403. Est ce que quelqu'un a réussi a trouvé  d'ou ça pourrait venir ?
