### ISSUE TITLE
Requested startAT time doesnt match allocine website time

### ISSUE THREAD

**Issue by Malinx95** [gromez/allocine-api#20]
hello, i have tested the updated exemple for the graphql api and it works. But when i am looking for the showtimes on allocine, Some movies showtimes doesnt correspond to the api request result.
for exemple the showtime for "bac nord" doesnt correspond.
Here is my code : 
[test.txt](https://github.com/gromez/allocine-api/files/7324748/test.txt)

and here is the result : 
![Capture d’écran 2021-10-11 205124](https://user-images.githubusercontent.com/56080345/136839855-34204a77-552d-49c8-9eff-49847a917050.png)

and here is the allocine page : https://www.allocine.fr/seance/d-1/salle_gen_csalle=P0591.html

Is it my code or is it the api ?

**Comment by gromez** [comment]
What's the problem, it matches?

![Screenshot_20211011-213747_Chrome](https://user-images.githubusercontent.com/179893/136846628-eaf2056c-3d9e-4823-b62e-eebee5399bc6.png)

**Comment by gromez** [comment]
https://github.com/gromez/allocine-api/commit/1ec5851e92708d8017f7959952f3943dc069084b
