### ISSUE TITLE
API ne fonctionne plus !

### ISSUE THREAD

**Issue by miranos** [gromez/allocine-api#9]
Bonsoir,

Avez vous un autre code partner s'il vous plait ?

Merci

**Comment by gromez** [comment]
Testé à l'instant via le script https://github.com/gromez/allocine-api/blob/master/PHP/get.php
Ca marche très bien

**Comment by miranos** [comment]
Excellent travail !

ça marche parfaitement, enfaite j'ai utilisé celui qui se trouve sur ce site:
https://wiki.gromez.fr/dev/api/allocine_v3

Il n'est pas mis à jours ... il vaut mieux le faire puis que quand quelqu'un écrit API ALLOCINE c'est le premier résultat sur google.

Merci encore.

**Comment by miranos** [comment]
Par contre une question si possible.

Comment obtenir ces valeurs en cas de changement ?

```
define('ALLOCINE_PARTNER_KEY', '100043982026');
define('ALLOCINE_SECRET_KEY', '29d185d98c984a359e6e6f26a0474269');
```

Merci
